version: "3.3"

services:
  orthoepy-bot:
    container_name: bot
    image: ekiauhce/orthoepy-bot:latest
    build: ./
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    env_file:
      .env