version: "3.3"

services:
  orthoepy-bot:
    container_name: bot
    image: ekiauhce/orthoepy-bot
    build: ./
    ports:
    - "8443:8443"
    env_file:
      - .env
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    env_file:
      .env